bootloader.h
APP1_START
APP2_START
FLASH_SECTOR_SIZE
FLASH_SECTOR_SIZE_USER
ERASE_FLASH_MEMORY
FLASHING_START
FLASHING_FINISH
FLASHING_ABORT
BootloaderMode
AppSelection
FlashStatus
typedef void() application_t(void)(void)
AppSelection App
Referenced by eraseMemory, flashWord, unlockFlashAndEraseMemory.
uint32_t Flashed_offset
Referenced by eraseMemory, flashWord.
FlashStatus flashStatus
Referenced by eraseMemory, lockFlash, messageHandler, unlockFlashAndEraseMemory.
USBD_HandleTypeDef hUsbDeviceFS
Referenced by deinitEverything.
void bootloaderInit()
void flashWord(uint32_t word)
References App, App1, APP1_START, APP2_START, Flashed_offset, readWord.
uint32_t readWord(uint32_t address)
Referenced by flashWord.
void eraseMemory()
References App, App1, Erased, errorBlink, Flashed_offset, flashStatus.
Referenced by messageHandler.
void unlockFlashAndEraseMemory()
References App, App1, Erased, errorBlink, flashStatus, Unlocked.
Referenced by messageHandler.
void lockFlash()
References flashStatus, Locked.
Referenced by messageHandler.
void jumpToApp()
void deinitEverything()
References hUsbDeviceFS, LD5_GPIO_Port, LD5_Pin, LD6_GPIO_Port, LD6_Pin.
Referenced by jumpToApp.
uint8_t string_compare(char array1[], char array2[], uint16_t length)
Referenced by messageHandler.
void errorBlink()
References LD5_GPIO_Port, LD5_Pin.
Referenced by eraseMemory, unlockFlashAndEraseMemory.
void messageHandler(uint8_t *Buf)
References ERASE_FLASH_MEMORY, eraseMemory, FLASHING_ABORT, FLASHING_FINISH, FLASHING_START, flashStatus, lockFlash, string_compare, Unlocked, unlockFlashAndEraseMemory.