.TH "C:/Users/mmitr/STM32CubeIDE/workspace_1.6.0/STM32F407VGT_Bootloader/Core/Src/bootloader.c" 3 "Thu Aug 5 2021" "STM32F407VGT_BL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/mmitr/STM32CubeIDE/workspace_1.6.0/STM32F407VGT_Bootloader/Core/Src/bootloader.c
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBbootloaderInit\fP ()"
.br
.ti -1c
.RI "void \fBflashWord\fP (uint32_t dataToFlash)"
.br
.ti -1c
.RI "uint32_t \fBreadWord\fP (uint32_t address)"
.br
.ti -1c
.RI "void \fBeraseMemory\fP ()"
.br
.ti -1c
.RI "void \fBunlockFlashAndEraseMemory\fP ()"
.br
.ti -1c
.RI "void \fBlockFlash\fP ()"
.br
.ti -1c
.RI "void \fBjumpToApp\fP (const uint32_t address)"
.br
.ti -1c
.RI "void \fBdeinitEverything\fP ()"
.br
.ti -1c
.RI "uint8_t \fBstring_compare\fP (char array1[], char array2[], uint16_t length)"
.br
.ti -1c
.RI "void \fBerrorBlink\fP ()"
.br
.ti -1c
.RI "void \fBmessageHandler\fP (uint8_t *Buf)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void bootloaderInit ()"

.SS "void deinitEverything ()"

.SS "void eraseMemory ()"

.SS "void errorBlink ()"

.SS "void flashWord (uint32_t dataToFlash)"

.SS "void jumpToApp (const uint32_t address)"

.SS "void lockFlash ()"

.SS "void messageHandler (uint8_t * Buf)"

.SS "uint32_t readWord (uint32_t address)"

.SS "uint8_t string_compare (char array1[], char array2[], uint16_t length)"

.SS "void unlockFlashAndEraseMemory ()"

.SH "Author"
.PP 
Generated automatically by Doxygen for STM32F407VGT_BL from the source code\&.
