.TH "JumpStruct" 3 "Thu Aug 5 2021" "STM32F407VGT_BL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JumpStruct
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <bootloader\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint32_t \fBstack_addr\fP"
.br
.ti -1c
.RI "\fBapplication_t\fP * \fBfunc_p\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "\fBapplication_t\fP* func_p"

.SS "uint32_t stack_addr"


.SH "Author"
.PP 
Generated automatically by Doxygen for STM32F407VGT_BL from the source code\&.
