.TH "C:/Users/mmitr/STM32CubeIDE/workspace_1.6.0/STM32F407VGT_Bootloader/Core/Inc/stm32f4xx_it.h" 3 "Thu Aug 5 2021" "STM32F407VGT_BL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/mmitr/STM32CubeIDE/workspace_1.6.0/STM32F407VGT_Bootloader/Core/Inc/stm32f4xx_it.h \- This file contains the headers of the interrupt handlers\&.  

.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBNMI_Handler\fP (void)"
.br
.RI "This function handles Non maskable interrupt\&. "
.ti -1c
.RI "void \fBHardFault_Handler\fP (void)"
.br
.RI "This function handles Hard fault interrupt\&. "
.ti -1c
.RI "void \fBMemManage_Handler\fP (void)"
.br
.RI "This function handles Memory management fault\&. "
.ti -1c
.RI "void \fBBusFault_Handler\fP (void)"
.br
.RI "This function handles Pre-fetch fault, memory access fault\&. "
.ti -1c
.RI "void \fBUsageFault_Handler\fP (void)"
.br
.RI "This function handles Undefined instruction or illegal state\&. "
.ti -1c
.RI "void \fBSVC_Handler\fP (void)"
.br
.RI "This function handles System service call via SWI instruction\&. "
.ti -1c
.RI "void \fBDebugMon_Handler\fP (void)"
.br
.RI "This function handles Debug monitor\&. "
.ti -1c
.RI "void \fBPendSV_Handler\fP (void)"
.br
.RI "This function handles Pendable request for system service\&. "
.ti -1c
.RI "void \fBSysTick_Handler\fP (void)"
.br
.RI "This function handles System tick timer\&. "
.ti -1c
.RI "void \fBOTG_FS_IRQHandler\fP (void)"
.br
.RI "This function handles USB On The Go FS global interrupt\&. "
.in -1c
.SH "Detailed Description"
.PP 
This file contains the headers of the interrupt handlers\&. 


.PP
\fBAttention\fP
.RS 4

.RE
.PP
.SS "(C) Copyright (c) 2021 STMicroelectronics\&. All rights reserved\&."
.PP
This software component is licensed by ST under Ultimate Liberty license SLA0044, the 'License'; You may not use this file except in compliance with the License\&. You may obtain a copy of the License at: www\&.st\&.com/SLA0044 
.SH "Function Documentation"
.PP 
.SS "void BusFault_Handler (void)"

.PP
This function handles Pre-fetch fault, memory access fault\&. 
.SS "void DebugMon_Handler (void)"

.PP
This function handles Debug monitor\&. 
.SS "void HardFault_Handler (void)"

.PP
This function handles Hard fault interrupt\&. 
.SS "void MemManage_Handler (void)"

.PP
This function handles Memory management fault\&. 
.SS "void NMI_Handler (void)"

.PP
This function handles Non maskable interrupt\&. 
.SS "void OTG_FS_IRQHandler (void)"

.PP
This function handles USB On The Go FS global interrupt\&. 
.SS "void PendSV_Handler (void)"

.PP
This function handles Pendable request for system service\&. 
.SS "void SVC_Handler (void)"

.PP
This function handles System service call via SWI instruction\&. 
.SS "void SysTick_Handler (void)"

.PP
This function handles System tick timer\&. 
.SS "void UsageFault_Handler (void)"

.PP
This function handles Undefined instruction or illegal state\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for STM32F407VGT_BL from the source code\&.
